V3.0.0 fork cldr42 updates
coupa/countries pull request #9
Opened 2023-03-08 17:24 UTC by rakris01

Updated countries yaml file with latest CLDR Data.

Deleted files which do not have any subdivisions

List of files updated.
lib/countries/data/subdivisions/AF.yaml
lib/countries/data/subdivisions/AG.yaml
lib/countries/data/subdivisions/AI.yaml
lib/countries/data/subdivisions/AL.yaml
lib/countries/data/subdivisions/AS.yaml
lib/countries/data/subdivisions/AX.yaml
lib/countries/data/subdivisions/AZ.yaml
lib/countries/data/subdivisions/BA.yaml
lib/countries/data/subdivisions/BH.yaml
lib/countries/data/subdivisions/BI.yaml
lib/countries/data/subdivisions/BM.yaml
lib/countries/data/subdivisions/BS.yaml
lib/countries/data/subdivisions/BY.yaml
lib/countries/data/subdivisions/BZ.yaml
lib/countries/data/subdivisions/CD.yaml
lib/countries/data/subdivisions/CI.yaml
lib/countries/data/subdivisions/CK.yaml
lib/countries/data/subdivisions/CL.yaml
lib/countries/data/subdivisions/CN.yaml
lib/countries/data/subdivisions/CV.yaml
lib/countries/data/subdivisions/CZ.yaml
lib/countries/data/subdivisions/DJ.yaml
lib/countries/data/subdivisions/DK.yaml
lib/countries/data/subdivisions/EE.yaml
lib/countries/data/subdivisions/EH.yaml
lib/countries/data/subdivisions/ET.yaml
lib/countries/data/subdivisions/FI.yaml
lib/countries/data/subdivisions/FO.yaml
lib/countries/data/subdivisions/FR.yaml
lib/countries/data/subdivisions/GB.yaml
lib/countries/data/subdivisions/GG.yaml
lib/countries/data/subdivisions/GH.yaml
lib/countries/data/subdivisions/GL.yaml
lib/countries/data/subdivisions/GQ.yaml
lib/countries/data/subdivisions/GR.yaml
lib/countries/data/subdivisions/GT.yaml
lib/countries/data/subdivisions/GU.yaml
lib/countries/data/subdivisions/HK.yaml
lib/countries/data/subdivisions/ID.yaml
lib/countries/data/subdivisions/IM.yaml
lib/countries/data/subdivisions/IN.yaml
lib/countries/data/subdivisions/IQ.yaml
lib/countries/data/subdivisions/IR.yaml
lib/countries/data/subdivisions/IS.yaml
lib/countries/data/subdivisions/IT.yaml
lib/countries/data/subdivisions/JE.yaml
lib/countries/data/subdivisions/KE.yaml
lib/countries/data/subdivisions/KP.yaml
lib/countries/data/subdivisions/KY.yaml
lib/countries/data/subdivisions/KZ.yaml
lib/countries/data/subdivisions/LA.yaml
lib/countries/data/subdivisions/LR.yaml
lib/countries/data/subdivisions/LU.yaml
lib/countries/data/subdivisions/LV.yaml
lib/countries/data/subdivisions/MA.yaml
lib/countries/data/subdivisions/MC.yaml
lib/countries/data/subdivisions/MD.yaml
lib/countries/data/subdivisions/ME.yaml
lib/countries/data/subdivisions/MH.yaml
lib/countries/data/subdivisions/MK.yaml
lib/countries/data/subdivisions/ML.yaml
lib/countries/data/subdivisions/MP.yaml
lib/countries/data/subdivisions/MR.yaml
lib/countries/data/subdivisions/MS.yaml
lib/countries/data/subdivisions/MU.yaml
lib/countries/data/subdivisions/MV.yaml
lib/countries/data/subdivisions/MW.yaml
lib/countries/data/subdivisions/MX.yaml
lib/countries/data/subdivisions/NC.yaml
lib/countries/data/subdivisions/NL.yaml
lib/countries/data/subdivisions/NO.yaml
lib/countries/data/subdivisions/NP.yaml
lib/countries/data/subdivisions/NZ.yaml
lib/countries/data/subdivisions/OM.yaml
lib/countries/data/subdivisions/PA.yaml
lib/countries/data/subdivisions/PF.yaml
lib/countries/data/subdivisions/PG.yaml
lib/countries/data/subdivisions/PH.yaml
lib/countries/data/subdivisions/PK.yaml
lib/countries/data/subdivisions/PL.yaml
lib/countries/data/subdivisions/PM.yaml
lib/countries/data/subdivisions/PR.yaml
lib/countries/data/subdivisions/QA.yaml
lib/countries/data/subdivisions/SC.yaml
lib/countries/data/subdivisions/SD.yaml
lib/countries/data/subdivisions/SG.yaml
lib/countries/data/subdivisions/SH.yaml
lib/countries/data/subdivisions/SJ.yaml
lib/countries/data/subdivisions/SL.yaml
lib/countries/data/subdivisions/SO.yaml
lib/countries/data/subdivisions/ST.yaml
lib/countries/data/subdivisions/SV.yaml
lib/countries/data/subdivisions/TD.yaml
lib/countries/data/subdivisions/TF.yaml
lib/countries/data/subdivisions/TK.yaml
lib/countries/data/subdivisions/TT.yaml
lib/countries/data/subdivisions/TV.yaml
lib/countries/data/subdivisions/TW.yaml
lib/countries/data/subdivisions/TZ.yaml
lib/countries/data/subdivisions/UA.yaml
lib/countries/data/subdivisions/UG.yaml
lib/countries/data/subdivisions/VI.yaml
lib/countries/data/subdivisions/VN.yaml
lib/countries/data/subdivisions/YT.yaml
lib/countries/data/subdivisions/ZA.yaml

List of files deleted
lib/countries/data/subdivisions/AI.yaml
lib/countries/data/subdivisions/AS.yaml
lib/countries/data/subdivisions/AX.yaml
lib/countries/data/subdivisions/BM.yaml
lib/countries/data/subdivisions/CK.yaml
lib/countries/data/subdivisions/EH.yaml
lib/countries/data/subdivisions/FO.yaml
lib/countries/data/subdivisions/GG.yaml
lib/countries/data/subdivisions/GU.yaml
lib/countries/data/subdivisions/HK.yaml
lib/countries/data/subdivisions/IM.yaml
lib/countries/data/subdivisions/JE.yaml
lib/countries/data/subdivisions/MP.yaml
lib/countries/data/subdivisions/MS.yaml
lib/countries/data/subdivisions/NC.yaml
lib/countries/data/subdivisions/PF.yaml
lib/countries/data/subdivisions/PM.yaml
lib/countries/data/subdivisions/SJ.yaml
lib/countries/data/subdivisions/TF.yaml
lib/countries/data/subdivisions/TK.yaml
lib/countries/data/subdivisions/VI.yaml
lib/countries/data/subdivisions/YT.yaml

2023-03-09 02:21 UTC, davidejorgensen requested changes
Per our slack chat @rakris01  - The removal of "comments:" field and addition of # comment values "#No Change in CLDR" to all of the entries that didn't change causes a very large number of changes to appear in the diff even though nothing changed (for these particular entries). Per our chat can we exclude these changes from the ymls and then just use the diff spreadsheet you prepared for the information about what should or should not change, so we can check that against the PR instead?

2023-03-09 19:17 UTC, davidejorgensen commented on lib/countries/data/subdivisions/DK.yaml
>  '015':
Is this approach of keeping the ID keyname (eg. "'015':") and deleting the name (eg. "translations:" "en:" value... eg. "København") the proper way to do a 'Removed from CLDR' operation?

It seemed like the other removals (eg. CZ.yml, removing ALL the "JC:" values) was more thorough. Why are these removals handled differently?

2023-03-09 19:24 UTC, davidejorgensen commented on lib/countries/data/subdivisions/EE.yaml
> +    ar:
Looks like we lost a lot of translated country names when the "State Code is Changed"... Is this an issue with the processing/script? Or actual deletion of the relevant translations from the CLDR sources? Please double-check.

2023-03-09 19:32 UTC, davidejorgensen commented on lib/countries/data/subdivisions/ET.yaml
> +SI:
Here in ET.yml for the SI subdivision, and for other addtions in EE.yml I noticed there are no non-English translations for the subdivision names... Is this a script/processing issue, or are the actual CLDR sources missing these translations as well? I'm asking because there seems to be non-English translations available for other subdivisions within the same country.

2023-03-09 19:38 UTC, davidejorgensen commented on lib/countries/data/subdivisions/FI.yaml
> +#Removed from CLDR -- '01':
Based on the PR this looks like FI.yaml changes subdivision 01 from "Åland Islands" to "Southwest Finland" -- But according to the spreadsheet subdivision 01 is supposed to be 'Removed from CLDR'... also, the spreadsheet says "Southwest Finland" is supposed to be subdivision 19, "No Change" so why is it now appearing here as Subdivision 01?

2023-03-09 19:58 UTC, davidejorgensen requested changes
The reduced comments worked very well. Was able to review much more deeply. Please see additional questions/issues.

2023-03-10 01:41 UTC, rakris01 commented on lib/countries/data/subdivisions/DK.yaml
>  '015':
It was a script issue. Fixed it, now the correct file is checked in.

2023-03-10 01:41 UTC, rakris01 commented on lib/countries/data/subdivisions/ET.yaml
> +SI:
There is only English names available for these subdivisions. CLDR data will be updated in the next CLDR update.

2023-03-10 19:22 UTC, rakris01 commented on lib/countries/data/subdivisions/EE.yaml
> +    ar:
There is only English names available for these subdivisions. CLDR data will be updated in the next CLDR update.

2023-03-10 20:53 UTC, davidejorgensen approved these changes
Comments sufficiently resolved in slack and PR replies.
LGTM

2023-03-10 21:06 UTC, aniketgade01 approved these changes

2023-03-10 21:16 UTC, merged